### ISSUE TITLE
Error reporting for missing config file doesn't work

### ISSUE THREAD

**Issue by krasnoukhov** [Sergio-Muriel/theoldreader-cli#3]
Here is the output, basically:

```
$ ./gui.pl 
Can't locate object method "output_error" via package "TheOldReader::Gui" at TheOldReader/Config.pm line 24.
```

**Comment by Sergio-Muriel** [comment]
Hello Dmitri!

Thank you for all the PR's and the bug report!
I just fixed that one.

**Comment by krasnoukhov** [comment]
Hey Sergio, thanks for merging. Your project looks really nice! I'm going to create a few more issues if you don't mind.
