### ISSUE TITLE
configuration repeats indefinitely "Display unread desktop notifications [Y/n]:"

### ISSUE THREAD

**Issue by mkaisercross** [Sergio-Muriel/theoldreader-cli#6]
When running for the first time the configuration prompts for several settings. When you try answer "Display unread desktop notifications [Y/n]:" the prompt is repeated indefinitely whether you said yes or no.

Let me know if I can provide any more details.

**Comment by Sergio-Muriel** [comment]
Hi Mkaisercross!
It's now fixed on "master" branch.

Thank you for the feedback
